### PR TITLE
Bump template-haskell and th-abstraction for GHC 9.6.1, update CI

### PR DESCRIPTION
**Pull request by andreasabel**
CI run at: https://github.com/andreasabel/linear-generics/actions/runs/4478302896/jobs/7870903370
Failing because of ` -Werror=incomplete-patterns`:
https://github.com/andreasabel/linear-generics/actions/runs/4478302896/jobs/7870903540#step:18:31
```
src/Generics/Linear/TH/Internal.hs:328:20: error: [-Wincomplete-patterns, -Werror=incomplete-patterns]
    Pattern match(es) are non-exhaustive
    In a case alternative:
        Patterns of type ‘DatatypeVariant’ not matched: TypeData
    |
    |     let variant_ = case variant of
    |                    ^^^^^^^^^^^^^^^...
```
@RyanGlScott @treeowl Do you want to fix this warning before releasing a GHC-9.6 compatible version to hackage?
(It is a bit odd that the [released version says `tested-with: GHC == 9.6.1`](https://github.com/linear-generics/linear-generics/blob/d43360e646cf2c0a510b5ea538c3d590a5b12722/linear-generics.cabal#L65) but does not support it.)

### CODE REVIEW

**Comment by treeowl** [comment]
Yes, we want to fix that.

**Comment by treeowl** [comment]
> It is a bit odd that the [released version says `tested-with: GHC == 9.6.1`](https://github.com/linear-generics/linear-generics/blob/d43360e646cf2c0a510b5ea538c3d590a5b12722/linear-generics.cabal#L65) but does not support it.

I believe that's because of the weird way `haskell-ci` handles pre-release GHC versions. As you can see, [adding 9.6.1](https://github.com/linear-generics/linear-generics/pull/17) originally didn't cause any CI problems, and it's the only way I *personally* know to get CI to test with the pre-release. But as you saw, regenerating with the latest `haskell-ci` (and therefore the released GHC) triggered troubles.

**Comment by andreasabel** [comment]
> > It is a bit odd that the [released version says `tested-with: GHC == 9.6.1`](https://github.com/linear-generics/linear-generics/blob/d43360e646cf2c0a510b5ea538c3d590a5b12722/linear-generics.cabal#L65) but does not support it.
> 
> I believe that's because of the weird way `haskell-ci` handles pre-release GHC versions. As you can see, [adding 9.6.1](https://github.com/linear-generics/linear-generics/pull/17) originally didn't cause any CI problems, and it's the only way I _personally_ know to get CI to test with the pre-release. But as you saw, regenerating with the latest `haskell-ci` (and therefore the released GHC) triggered troubles.

To avoid this oddity, I patched haskell-ci to use **9.6.0** as identifier for the prereleases rather than 9.6.1:
https://github.com/andreasabel/haskell-ci/commit/fecc5eaf9122584e6fbbfbc762d251bfa8bb37a0
Here is the relevant discussion with @phadej (or rather just an unheard plea) about using `.0` for prereleases:
- https://github.com/haskell-CI/haskell-ci/issues/631

**Comment by treeowl** [comment]
I just added a commit to deal with the errors. Does everything look okay to you?

**Comment by treeowl** [comment]
UGH. Silliness.

**Comment by phadej** [comment]
```
Patterns of type ‘DatatypeVariant’ not matched: TypeData
```

is due `th-abstraction-0.5.0.0`, not due building with GHC-9.6.

Please barf at the right tree.

**Comment by treeowl** [comment]
Let's all be civil, please. The issue is that it was not obvious, looking at the Cabal file, that the GHC 9.6.1 tests were compiled with `allow-newer`. I believe @andreasabel was suggesting that if the pre-release were called 9.6.0, then that would send the right message, so I wouldn't be confused about why things started failing.

**Pull request merged**
